version: '3'
services:
  app:
    image: blog-app-image 
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    networks:
      - postgres_data

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: Blogsite
      POSTGRES_PASSWORD: root
    networks:
      - postgres_data

  prisma-migrate:
    image: blog-app-image  # Replace 'blog-app-image' with the actual name of your Node.js Docker image
    depends_on:
      - db
    entrypoint: /bin/sh
    command:
      - '-c'
      - 'npx prisma migrate up --experimental'
    networks:
      - postgres_data

networks:
  postgres_data:
